# Generated by Django 6.0.3 on 2026-05-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('type', models.CharField(blank=True, choices=[('boys', 'Boys'), ('girls', 'Girls'), ('room', 'Room')], max_length=20)),
                ('images', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('sharing_media', models.JSONField(blank=True, default=dict)),
                ('sharing_images', models.JSONField(blank=True, default=dict)),
                ('room_sharing', models.JSONField(blank=True, default=dict)),
                ('vacancy', models.JSONField(blank=True, default=dict)),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel_users', models.ManyToManyField(blank=True, related_name='joined_hostels', to='users.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='owners.owner')),
            ],
            options={
                'indexes': [models.Index(fields=['area'], name='hostels_app_area_39bac9_idx'), models.Index(fields=['type'], name='hostels_app_type_fd1320_idx'), models.Index(fields=['rating'], name='hostels_app_rating_c4e64a_idx')],
            },
        ),
    ]
