# Generated by Django 6.0.3 on 2026-05-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels_app', '0001_initial'),
        ('owners', '0002_owner_otp_owner_otp_created_at'),
        ('users', '0002_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('owner', 'Owner'), ('user', 'User')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('sharing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sharing_type', models.CharField(max_length=50)),
                ('vacancy_deducted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_requests', to='hostels_app.hostel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_requests', to='owners.owner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_requests', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner'], name='requests_ap_owner_i_6fcac6_idx'), models.Index(fields=['user'], name='requests_ap_user_id_24b5ed_idx'), models.Index(fields=['hostel'], name='requests_ap_hostel__681aec_idx'), models.Index(fields=['status'], name='requests_ap_status_36fb75_idx')],
            },
        ),
    ]
