# Generated by Django 6.0.3 on 2026-05-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vacancy_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
