# Generated by Django 6.0.3 on 2026-05-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('joined_hostel_id', models.CharField(blank=True, max_length=64, null=True)),
                ('joined_hostel_name', models.CharField(blank=True, max_length=255)),
                ('joined_owner_id', models.CharField(blank=True, max_length=64, null=True)),
                ('joined_sharing_type', models.CharField(blank=True, max_length=50)),
                ('joined_sharing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
