# Generated by Django 6.0.3 on 2026-06-19 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels_app', '0001_initial'),
        ('users', '0002_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_hostel_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joined_hostel_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joined_owner_id',
        ),
        migrations.AddField(
            model_name='user',
            name='joined_hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='hostels_app.hostel'),
        ),
    ]
